import { Bug, Check, ChevronRight, LockKeyhole, Radar, Shield, Sparkles, Star, UploadCloud } from 'lucide-react';
import { Link } from 'react-router-dom';
import ThemeToggle from '../components/ThemeToggle';

const features = [
  [Bug, 'Error detection', 'See the file, the line and the reason for every issue in your project.'],
  [Star, 'Quality score', 'One simple score out of 100 with reliability, security and maintainability ratings.'],
  [Sparkles, 'AI fixes', 'Generate and inspect suggested code changes before updating your project.'],
  [LockKeyhole, 'Security checks', 'Spot risky patterns early, before they reach your users.'],
  [Shield, 'GitHub pull request reviews', 'Get a DataGuard review comment on every pull request.'],
  [Radar, 'AI Radar', 'Explore tool suggestions and workflow ideas in the AI Radar preview.'],
];

export default function Landing() {
  return <div className="landing-page reference-home">
    <nav className="landing-nav"><Link to="/" className="landing-brand"><Shield size={23} fill="currentColor" />DataGuard AI</Link><div className="landing-links"><a href="#features">Features</a><a href="#github-app">GitHub App</a><Link to="/ai-radar">AI Radar</Link><ThemeToggle /><Link to="/login">Login</Link><Link className="pill-button" to="/login?mode=register">Register</Link></div></nav>
    <main>
      <section className="reference-hero"><div className="reference-hero-copy"><h1>Guard Your Code.<br /><span>Build With Confidence.</span></h1><p>DataGuard AI analyzes your software project, identifies quality and security issues, and explains how to improve them.</p><div className="reference-hero-actions"><Link className="pill-button" to="/login"><UploadCloud size={17} />Upload a project</Link><Link className="reference-secondary" to="/ai-radar">Explore AI Radar</Link></div><small>AI-assisted analysis. Always review suggested changes before applying them.</small></div><div className="reference-visual"><div className="reference-bot" role="img" aria-label="A rotating DataGuard robot"><i><b /><b /></i></div><span>Code Here</span></div></section>
      <section className="reference-section" id="features"><header><h2>Everything you need to ship clean code</h2><p>From the first scan to the final fix, DataGuard AI keeps you in control.</p></header><div className="reference-features">{features.map(([Icon, title, text]) => <article className="reference-card" key={title}><div className="reference-icon"><Icon size={22} /></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="reference-section"><header><h2>How it works</h2></header><div className="reference-steps"><article><b>1</b><h3>Upload your project</h3><p>Drop a ZIP archive into your dashboard. Nothing to install.</p></article><article><b>2</b><h3>Watch the quality check</h3><p>The status bar shows each stage until your score is ready.</p></article><article><b>3</b><h3>Review suggested fixes</h3><p>Inspect and copy suggested changes before updating your project.</p></article></div></section>
      <section className="reference-split" id="github-app"><div className="reference-pr"><div className="reference-pr-head"><span>⌁</span><b>Add checkout validation</b><small>#42</small></div><p>sai opened this pull request · 2 files changed</p><div className="reference-review"><b>♢ &nbsp; dataguard-ai</b><small>bot commented 2 minutes ago</small><hr /><strong>Code review · Quality score 82/100</strong><p><em>Critical</em> · app/main.js:24 · Undefined variable <code>totl</code>. Rename it to <code>total</code>.</p><p>Minor · utils/api.js:57 · Unused function <code>oldFormat</code>.</p><small>Reviewed by DataGuard AI. Always check suggestions before merging.</small></div></div><div><span className="reference-tag">GITHUB APP</span><h2>Code review right inside your pull requests</h2><p>Install DataGuard AI on GitHub and receive a review comment when someone opens a pull request. See the quality score, findings and where to fix them.</p><ul><li><Check />A quality score out of 100</li><li><Check />Every issue with its file and line</li><li><Check />Clear comments on what to improve</li></ul><a className="pill-button" href="https://github.com/apps/dataguard-ai" target="_blank" rel="noreferrer">Get the GitHub App <ChevronRight size={16} /></a><small>Opens GitHub. You install and manage the app there.</small></div></section>
      <section className="reference-section reference-report"><div><span className="reference-tag">SAMPLE REPORT</span><h2>See exactly what to fix</h2><p>No wall of warnings. Every issue comes with its location, severity and a suggested fix.</p><ul><li><Check />Clear diffs you can read at a glance</li><li><Check />Review and apply fixes one at a time</li><li><Check />Keep control of every change</li></ul></div><div className="reference-score"><div className="reference-score-ring">78</div><div><b>Quality check complete</b><p>3 issues · Gate passed</p></div><article><small>CRITICAL &nbsp; app/main.js:24</small><b>Undefined variable “totl”</b><code>- console.log(totl);<br /><i>+ console.log(total);</i></code></article></div></section>
      <section className="reference-radar"><span className="reference-tag">NEW</span><h2>Meet AI Radar</h2><p>Describe your project to see tool suggestions or a step-by-step workflow preview.</p><div><span>Find tools by task</span><span>Build workflows</span><span>Save your stack</span></div><Link className="pill-button" to="/ai-radar">Explore AI Radar <ChevronRight size={16} /></Link><small>Recommendations currently come from a server preview.</small></section>
      <section className="reference-section reference-faq"><header><h2>Frequently asked questions</h2></header><details><summary>Which languages are supported?</summary><p>JavaScript, TypeScript, Python, Java and C++ to start.</p></details><details><summary>Is my code kept private?</summary><p>Your uploads stay inside your account.</p></details><details><summary>Can I trust the AI suggestions?</summary><p>Always review a suggested change before applying it.</p></details><details><summary>How does the GitHub App work?</summary><p>Install DataGuard AI from GitHub and choose your repositories. The app posts review comments on pull requests.</p></details></section>
    </main>
    <footer className="reference-footer"><b><Shield size={17} /> DataGuard AI</b><span>Review your code with confidence.</span><a href="#features">Features</a><a href="#github-app">GitHub App</a><Link to="/ai-radar">AI Radar</Link><small>© DataGuard AI</small></footer>
  </div>;
}
